// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxfahjczlpedfbqzmqvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4ZmFoamN6bHBlZGZicXptcXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDc3NzUsImV4cCI6MjA3MDAyMzc3NX0.JW8FXZYfhUahhw2FWJLUH7CRH41L8IQzeBblC1aXugE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});